commands/sdcli_go_integration, commands/sdcli_go_test
The commands to generate coverage after failing tests can mask the
non-zero exit code of a test failure. The result may be a green build
with failing tests.
=> Use correct exit codes after tests

.travis.yml, Dockerfile
The latest version of the sdcli container throws a warning due to compilation
errors when running the `sdcli go lint` command. Here's an example:
```bash
WARN [runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/asecurityteam/nexpose-asset-attributor/pkg/domain github.com/asecurityteam/nexpose-asset-attributor github.com/asecurityteam/nexpose-asset-attributor/pkg/assetattributor [github.com/asecurityteam/nexpose-asset-attributor/pkg/assetattributor.test] github.com/asecurityteam/nexpose-asset-attributor/pkg/handlers/v1 [github.com/asecurityteam/nexpose-asset-attributor/pkg/handlers/v1.test]]: pkg/domain/alias.go:1: /usr/local/go/src/internal/bytealg/compare_amd64.s:5:1: illegal character U+0023 '#' and 130 more errors: run `golangci-lint run …
```
=> Fix golangci compilation errors

Dockerfile, commands/sdcli_python_lint
Added SDCLI command to run pylint on a repository containing python code. Can be called with: sdcli python lint
=> Adding python linting to SDCLI

README.md, commands/sdcli_version
Added a command to print out the versions of the installed languages and programs on the sdcli image to make debugging easier.
Command can be called with:
> sdcli version
=> Sdcli version

commands/sdcli_go_dep
So, to avoid every repo's pipeline breaking while I transfer our projects from dep to go mod, I'm adding a small change to sdcli go dep to temporarily support both options. Once all repositories have been migrated to go mod, I will remove the dep ensure line completely.
=> Go mod migration

commands/sdcli_go_integration, commands/sdcli_go_lint, commands/sdcli_go_test
I've added a new round of changes to our go tooling to support both go mod and dep during the migration. These changes are temporary measure until all our repos are fully converted to go mod. I've added a -mod=vendor to our go test calls, as go test appears to not use the go mod-created vendor directory by default.
=> Adding go mod support to linter, integration, and unit testing tools.

commands/sdcli_version
**Before**
```
$ sdcli version
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
```
Reason -  docker does not pass TERM environment variable on (my ?) mac 
**After**
No error and color codes not rendered TERM is not set or is empty.
=> Add fallback for TERM value

commands/sdcli_go_coverage, commands/sdcli_go_dep, commands/sdcli_go_integration, commands/sdcli_go_lint, commands/sdcli_go_test
So, it looks like my last update wasn't enough to properly implement go mod vendoring support. Luckily, we can set a few environment variables that will ensure that all Golang functions will utilize go mod's vendor directory. Eventually, once we are ready to completely move away from dep, I will set these environment variables permanently in SDCLI's dockerfile.
=> Updating go tooling to support go mod vendoring

commands/sdcli_go_integration, commands/sdcli_go_test
Adding the `-race` flag to the go test commands to check for race conditions
in code.
=> Add `-race` flag to go test commands

commands/sdcli_yaml_lint
Fixing a problem where the -d option was being used which causes rules in the `.yamllint` file to be ignored. Based on the comment https://github.com/asecurityteam/sdcli/compare/remove-default-rule?expand=1#diff-015f890b87f84ecdc5c76284608ccafeR4 this is not how this was supposed to work.
What is more ideal is you allow projects to configure their own .yamllint which once you remove the -d option you can do.
=> Removed rules that override config file

Dockerfile
Updated Dockerfile to reference NodeJS version 12 instead of 11. 
Linked below is a reference chart to show why the upgrade is necessary.
[Node Version Chart](https://nodejs.org/en/about/releases/)
=> updated deb.nodesource to reference nodejs 12 instead of 11

Dockerfile, README.md, commands/sdcli_python_lint, commands/sdcli_version
Pylint does not support directory exclusion by path in configuration file. Therefore, we decided to switch Pylint to Flake8, as we need a better python linting tool for our project.
=> Change Python linting tool

Dockerfile
It looks like the older version we currently use causes issues similar to https://github.com/golangci/golangci-lint/issues/659 , which results in a subset of linter checks not running.
=> Update golangci to latest upstream version

Dockerfile
Update Go base image from `golang:1.17.2-buster` -> `golang:1.17.7-buster`.
Needed to appease [new requirements from BB Cloud](https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-Bitbucket-API-Requires-Latest-Version-of-Go/ba-p/1975819)
Also, updated the pip install for `ccextender`.
=> [PANG-1286] Update Go base image

Dockerfile
Update the source of `golangci-lint` as the old download path no longer exists. 
Used the official docs of the library to make the changes: https://golangci-lint.run/usage/install/#ci-installation
---
Quick demo to show that it worked. Was ran using the below command, with a locally built image with these changes as `sdcli:v1.2.6`
```
sdcli() {
local cwd="$(pwd)"
local gopath="${GOPATH}"
if [[ "${gopath}" == "" ]]; then
gopath=~/go # default gopath since 1.8
fi
local project_path=${cwd#"${gopath}/src/"}
docker run --rm -v "$(pwd -L):/go/src/${project_path}" \
-w "/go/src/${project_path}" \
sdcli:v1.2.6 "$@"
}
```
Running the linter in a repo where the previous version was failing:
```
❯ sdcli go lint
level=info msg="[config_reader] Used config file .golangci.yaml"
level=info …
```
=> PANG-1287 - Update `golangci-lint` source

Dockerfile, golang/tools.go, test/test_go_utils.py
* Fixes to paths for go deps to ensure binaries are installed in addition to sources
* Tests for binaries being there
* Removed version of golangci from Dockerfile, we no longer use it.
=> fixes to go tool installation and test to make sure those are installed

Dockerfile, docker-apt.list, test/test_packages.py
The debian oldstable that we are currently using is at EOL, about to come to LTS stage. The quality of LTS  with Debian is not same with what RH and Canonical provide, so we are better off with newer version. Version changes of various utilities match packages available in newer Debian version. https://wiki.debian.org/DebianReleases#Production_Releases related reading.
=> Update to latest Debian stable

commands/sdcli_go_integration
Run integration tests from all subdirectories of the `tests` directory.
Currently the `integration` command which runs integration tests only executes the test files which are directly the children of the `tests` directory. Basically `tests/*.go`
For a directory structure like this
```
tests
└── internal
└── sqldb
├── issue_integration_test.go
├── repository_integration_test.go
└── workspace_integration_test.go
```
the test files are currently not getting executed by the `integration` command.
To run integration tests from all subdirectories in the tests directory the command line argument is being updated from 
`go test ./tests` to 
`go test ./tests/...`.
=> Runs integration tests from all subdirectories in the tests directory

Dockerfile, docker-compose, test/test_docker.py
This adds a shim to emulate `docker-compose` using `docker compose` as we have code relying on existence of -compose and the change that removes it was published as v1. Also adds test for functioning `docker` and `docker-compose`
=> Fix missing docker-compose command

Dockerfile, docker-compose, test/test_docker.py
Apparently the `docker compose` and `docker-compose` are not 100% compatible. Providing both to allow legacy builds to keep working as is.
=> Provide compose plugin and cli tool simultanously, check versions

.github/workflows/docker-image.yml
M1 Macbooks use the `arm/v8` architecture, so we just need to change the `v7` -> `v8` ([source](https://en.wikipedia.org/wiki/Apple_M1)).
---
Example error:
Trying to run the sdcli on an M1 mac using the `latest` build, which builds as `linux/amd64` and `linux/arm/v7`
=> Add build for arm/v8, for M1 Mac compatability

.github/workflows/docker-image.yml
Arm/v8 is an updated version of the arm architecture, which the M1 Macbook uses. However, the M1 Macbook also uses runs under the 64-bit architecture, so we need to make sure we build the image using 64-bit, rather than the default 32-bit. 
---
Example of error when trying to run the `sdcli` via the `linux/arm/v8` build
=> Add build for arm64/v8, for M1 Mac compatability

.github/workflows/docker-image.yml, Makefile, commands/sdcli, test/run_tests.sh, test/test_cli.py
Our convention was to use `v` before SemVer, but it was lost during transition to GH actions.
=> Fix docker tagging

commands/sdcli_go_coverage, commands/sdcli_go_dep, commands/sdcli_go_integration, commands/sdcli_go_lint, commands/sdcli_go_test
* Add -buildvcs=false to default GOFLAGS as there is a regression ("feature") in golang starting with https://tip.golang.org/doc/go1.18 that is causing build/test steps to fail when VCS commands do not run Example: https://app.travis-ci.com/github/asecurityteam/transportd/builds/266710818#L290
* Changle handling of GOFLAGS in sdcli so that we can pass additional flags in environment, and those would be appended. This way we can override exiting parameters or add new w/o rebuilding images
=> GOFLAGS handling and buildvcs fix

.github/workflows/docker-image.yml
Trying to fix https://github.com/asecurityteam/sdcli/actions/runs/13272660135/job/37114071727#step:7:983
Apparently, the qemu setup step from docker uses a container with `:latest` tag and there is a regression 😨 .
Forcing it to the last known good hash of the image from https://github.com/asecurityteam/sdcli/actions/runs/13272580346/job/37055266682#step:3:109  seems to help
=> Update docker build and push action
